"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import {
  TestTube,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  Terminal,
  FileText,
  BarChart3,
  FlaskConical,
  Bug,
  Activity,
  ArrowRight,
  Layers,
  Cpu,
  ExternalLink
} from "lucide-react";

import {
  tests,
  derived,
  ci,
  security,
} from "@/data/facts";

/**
 * What each suite verifies — written by hand.
 *
 * The COUNTS are deliberately absent here. They come from tests.perSuite, which is
 * generated by `npm run docs:test-facts` from a real jest run, because the old
 * hand-typed table listed only 17 of the 26 suites and its totals did not add up
 * to the declared count.
 */
const suiteFocus: Record<string, string> = {
  "sandbox-security": "Fail-closed sandboxing (Seatbelt / bubblewrap / AppContainer + Job Objects), macOS adversarial OS-enforcement (AF_UNIX + signal confinement), command tokenizer, env sanitization",
  "windows-job-sandbox": "Windows AppContainer JS contract + runtime matrix (suspended AppContainer start, OS-enforced ACL allowlist, verified job, grandchild containment, secret isolation, KILL_ON_JOB_CLOSE)",
  "linux-bwrap-sandbox": "bubblewrap arg generation, namespace/unshare flags (pid/net/ipc/uts/user/cgroup), capability pre-flight fail-closed, Linux runtime enforcement",
  "security-fixes": "Regression suite for applied security fixes",
  "security-validator": "Blocklist / injection detection / risk classification",
  "directory-allowlist": "Path canonicalization, symlink traversal, read/write separation",
  "approval-ticket-security": "Ticket-based approval + capability-controller regression (audit findings)",
  "skill-loading": "Dynamic skill loading, validation allowlist, require-path resolution",
  extraction: "Web extractor, DOM parsing, content extraction edge cases (declared test blocks; it.each expands case count)",
  "tab-intelligence": "Tab intelligence, domain grouping, smart icons",
  "dom-engine": "DOM interaction engine, click/fill strategies",
  "component-tests": "React component behavior and props",
  "webauthn-service": "WebAuthn / FIDO2 challenge-response flow",
  automation: "OS automation layer (click / scroll / app launch)",
  "dom-handlers": "Browser DOM IPC handlers",
  "home-intelligence": "Home intelligence logic",
  "extensions.crx-verifier":
    "CRX3 signature enforcement — deliberately SKIPPED: verifyCrx() wedges the Node 24 OpenSSL verifier on CRX3 header parsing, which previously hung jest until the job timeout. Counted as skipped, never as passing, until the verifier is fixed. See Known Limits.",
  "extensions.permission-analyzer": "Chrome extension manifest permission analysis",
  "guardrails.origin-guard": "Origin trust levels and verb-scoped permission gates",
  "guardrails.prompt-injection": "Prompt-injection detection guards",
  "agent-api.registry": "Agent API tool registry and call routing",
  "agent.tab-lock": "Per-tab locking between concurrent agents",
  "agent.trust": "Agent trust-level assignment and scoping",
  "autofill.vault": "Encrypted autofill vault (AES-GCM, passphrase-derived key)",
  "theme": "Theme and UI-mode switching",
  snapshot: "Snapshot / accessibility-tree reference stability",
};

const testSuites = tests.perSuite.map((s) => ({
  file: s.suite,
  count: s.declared,
  passed: s.passed,
  skipped: s.skipped,
  focus: suiteFocus[s.suite] ?? "—",
}));

const crxSkip = tests.skipBreakdown.find((b) => b.reason.includes("CRX3"))?.count ?? 0;
const regressionCount =
  testSuites.find((s) => s.file === "security-fixes")?.count ?? 0;

const covered = [
  "Fail-closed by construction: every sandbox setup, validation, or policy failure returns a structured SANDBOX_* error and the command is never silently run unsandboxed — there is no automatic fallback path",
  "macOS Seatbelt — real OS enforcement: writing outside the directory allowlist is denied by the kernel and the file is verified absent; reading a secret outside the allowlist is denied; /tmp is writable; an IP network bind is denied; an AF_UNIX socket bind is denied; signalling a host process is denied while self-signal works; reading/writing through a symlink that escapes the allowlist is denied; a child process spawned by the target is still contained",
  "Linux bubblewrap — closed-by-default namespaces (pid/net/ipc/uts/user/cgroup + new session), correct --bind (write) vs --ro-bind (read-only) mapping, network denied by default, and fail-closed when bwrap is missing OR present-but-incapable of creating the required namespaces (the capability pre-flight)",
  "Windows AppContainer — policy fail-closed (missing runner, invalid allowlist, network-allowlist requests), result parsing, explicit isolation flags ({ filesystem:true, network:true, process:true }), plus a runtime matrix proving suspended AppContainer start + OS-enforced ACL allowlist + verified job assignment + grandchild containment + secret isolation + KILL_ON_JOB_CLOSE",
  "Explicit isolation contract — every result carries { filesystem, network, process }; macOS/Linux/Windows all report all-true when their platform sandbox is active, and any setup failure or unsandboxed run reports all-false",
  "Directory allowlist — fs.realpath() canonicalization, ../ traversal, symlink escape, read-only vs read-write separation, and invalid/missing-path rejection (never silently skipped)",
  "Command execution — the tokenizer preserves quoted arguments verbatim, separates direct execution from explicit shell mode, and never reconstructs a command via a string-joined sh -c; it is documented as a classifier, not a security parser",
  "Environment sanitization — API keys, tokens, and secrets are stripped from every sandboxed process; only an allowlisted set of non-credential variables passes through",
  `Security regressions — a ${regressionCount}-test regression suite re-verifying each applied security fix, plus approval-ticket tests that lock in the audit remediation`,
];

/**
 * Every sentence in here that contains a number is assembled from `ci` /
 * `tests` at render time. The prose around them (what the tests actually
 * verify, and what they don't) is hand-written and stays hand-written.
 */
const limitations = [
  `Runtime enforcement tests only EXECUTE on their own OS. ${ci.jobs.detail} Latest run [#${ci.latestRun.runNumber}](${ci.latestRun.url}) (${
    ci.latestRun.event
  }, ${ci.latestRun.date}) reported: ${ci.perJob
    .map(
      (j) =>
        `${j.name} on ${j.os} ${j.passed} passed / ${j.skipped} skipped / ${j.failed} failed of ${j.declared}`,
    )
    .join("; ")}. Suspended AppContainer start, OS-enforced ACL allowlist, verified job assignment, grandchild containment, secret isolation, and KILL_ON_JOB_CLOSE all return verified sandbox results.`,
  `The extensions.crx-verifier suite (${crxSkip} tests) is deliberately SKIPPED in CI: verifyCrx() trips a Node 24 OpenSSL decode path (ERR_OSSL_UNSUPPORTED / an event-loop-blocking native call) while parsing the CRX3 header, which previously hung the jest job until the ${ci.jobs.timeout} It is not counted as passing — it stays visible as a skipped suite (${crxSkip} skipped in the totals above) until the verifier's header parsing is fixed and the suite is re-enabled.`,
  "macOS Seatbelt OS-enforcement tests execute only on macOS; they pass on this machine and run in CI on macos-latest. The profile-generation and fail-closed config paths are asserted on every platform.",
  "These are unit and integration tests for core modules. They do NOT cover the full Electron UI, installers, MSIX/MSI packaging, or complete end-to-end user flows.",
  "A sandbox confines what code can do; it is not a proof that the AI's decisions are safe, nor a substitute for least-privilege OS accounts, patched dependencies, or simply not running untrusted code. See the security page's 'What this does NOT guarantee'.",
  `Counts above are declared it()/test() blocks as of ${derived.testGeneratedAt.slice(0, 10)} on ${derived.testEnvironment}; suites using it.each expand into more executed cases. Run npx jest (Node 24+, some deps are ESM) or check the CI run for jest.yml for exact pass/skip/fail numbers.`,
];

export default function TestingPage() {
  return (
    <div className="space-y-24">
      {/* Hero */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/5 px-5 py-2">
          <TestTube size={14} className="text-emerald-400" />
          <span className="text-[10px] font-black uppercase tracking-[0.4em] text-emerald-400">
            Testing &amp; Test Series
          </span>
        </div>

        <h1 className="mb-8 text-5xl font-black uppercase tracking-tighter sm:text-7xl">
          Test <span className="text-white/20">Series</span>
        </h1>

        <p className="max-w-3xl text-xl font-medium leading-relaxed text-white/50">
          Aartiq&apos;s core modules are verified with an automated Jest test suite. This page reports
          the real numbers, what is covered, and what is not.
        </p>

        {/* Stats — every figure below is imported from the generated test facts. */}
        <div className="mt-12 grid gap-6 sm:grid-cols-4">
          <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-6 text-center">
            <BarChart3 size={32} className="mx-auto mb-4 text-emerald-400" />
            <h3 className="text-3xl font-black text-emerald-400">{tests.suites.total}</h3>
            <p className="text-sm text-white/50">
              Test Suites ({tests.suites.passed} passing + {tests.suites.skipped} skipped)
            </p>
          </div>
          <div className="rounded-2xl border border-sky-500/20 bg-sky-500/5 p-6 text-center">
            <Layers size={32} className="mx-auto mb-4 text-sky-400" />
            <h3 className="text-3xl font-black text-sky-400">{tests.tests.declared}</h3>
            <p className="text-sm text-white/50">Total Tests (declared blocks)</p>
          </div>
          <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-6 text-center">
            <CheckCircle2 size={32} className="mx-auto mb-4 text-emerald-400" />
            <h3 className="text-3xl font-black text-emerald-400">{tests.tests.passed}</h3>
            <p className="text-sm text-white/50">Passing</p>
          </div>
          <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-6 text-center">
            <Activity size={32} className="mx-auto mb-4 text-amber-400" />
            <h3 className="text-3xl font-black text-amber-400">{tests.tests.skipped}</h3>
            <p className="text-sm text-white/50">
              Skipped · {tests.tests.failed} failing
            </p>
          </div>
        </div>

        <p className="mt-3 text-xs text-white/30">
          Counts generated on {derived.testEnvironment} at {derived.testGeneratedAt} — not typed.
          CI runs a different platform, so its per-job numbers differ; see the run below.
        </p>

        <a
          href={ci.latestRun.url}
          target="_blank"
          rel="noopener noreferrer"
          className="mt-8 inline-flex items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-5 py-2.5 text-sm font-bold text-emerald-300 transition-colors hover:bg-emerald-500/20"
        >
          <ShieldCheck size={16} />
          {ci.jobs.defined}/{ci.jobs.defined} jobs {ci.latestRun.conclusion} — run #
          {ci.latestRun.runNumber} ({ci.latestRun.event}, {ci.latestRun.date})
          <ExternalLink size={16} />
        </a>
      </motion.section>

      {/* Per-suite breakdown */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
      >
        <div className="mb-16">
          <p className="mb-4 text-[10px] font-black uppercase tracking-[0.5em] text-white/20">
            Breakdown
          </p>
          <h2 className="text-4xl font-black uppercase tracking-tighter sm:text-5xl">
            Test <span className="text-white/20">Suites</span>
          </h2>
        </div>

        <div className="overflow-hidden rounded-[2rem] border border-white/5 bg-white/[0.02]">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-white/5 text-[10px] font-black uppercase tracking-[0.3em] text-white/30">
                <th className="px-6 py-4">Suite</th>
                <th className="px-6 py-4">Tests</th>
                <th className="hidden px-6 py-4 md:table-cell">What it verifies</th>
              </tr>
            </thead>
            <tbody>
              {testSuites.map((s, i) => (
                <tr
                  key={s.file}
                  className={`border-b border-white/5 transition hover:bg-white/[0.02] ${
                    i === testSuites.length - 1 ? "border-b-0" : ""
                  }`}
                >
                  <td className="px-6 py-4 font-mono text-sm text-sky-400">{s.file}</td>
                  <td className="px-6 py-4">
                    <span className="inline-flex items-center gap-2 rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-bold text-emerald-400">
                      {s.count}
                    </span>
                    {s.skipped > 0 && (
                      <span className="ml-2 inline-flex items-center gap-1 rounded-full bg-amber-500/10 px-3 py-1 text-xs font-bold text-amber-400">
                        {s.skipped} skipped
                      </span>
                    )}
                  </td>
                  <td className="hidden px-6 py-4 text-sm text-white/50 md:table-cell">{s.focus}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </motion.section>

      {/* What's covered */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <div className="mb-16">
          <p className="mb-4 text-[10px] font-black uppercase tracking-[0.5em] text-white/20">
            Coverage
          </p>
          <h2 className="text-4xl font-black uppercase tracking-tighter sm:text-5xl">
            What&apos;s <span className="text-white/20">Covered</span>
          </h2>
        </div>

        <div className="rounded-[2rem] border border-emerald-500/20 bg-emerald-500/5 p-10">
          <ul className="space-y-4">
            {covered.map((item, i) => (
              <li key={i} className="flex items-start gap-4 text-sm text-white/60">
                <CheckCircle2 size={18} className="mt-0.5 shrink-0 text-emerald-400" />
                {item}
              </li>
            ))}
          </ul>
        </div>
      </motion.section>

      {/* Known limits */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
      >
        <div className="mb-16">
          <p className="mb-4 text-[10px] font-black uppercase tracking-[0.5em] text-white/20">
            Coverage Boundaries
          </p>
          <h2 className="text-4xl font-black uppercase tracking-tighter sm:text-5xl">
            Known <span className="text-amber-400">Limits</span>
          </h2>
        </div>

        <div className="rounded-[2rem] border border-amber-500/20 bg-amber-500/5 p-10">
          <div className="mb-8 flex items-center gap-4">
            <AlertTriangle size={40} className="text-amber-400" />
            <div>
              <h3 className="text-xl font-black uppercase tracking-wider">
                What this suite does NOT prove
              </h3>
              <p className="text-sm text-white/50">
                We would rather state these limits plainly than overstate coverage.
              </p>
            </div>
          </div>

          <ul className="space-y-4">
            {limitations.map((item, i) => (
              <li key={i} className="flex items-start gap-4 text-sm text-white/60">
                <AlertTriangle size={18} className="mt-0.5 shrink-0 text-amber-400" />
                {item}
              </li>
            ))}
          </ul>
        </div>
      </motion.section>

      {/* Run the tests */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
      >
        <div className="mb-16">
          <p className="mb-4 text-[10px] font-black uppercase tracking-[0.5em] text-white/20">
            Reproduce
          </p>
          <h2 className="text-4xl font-black uppercase tracking-tighter sm:text-5xl">
            Run the <span className="text-white/20">Tests</span>
          </h2>
        </div>

        <div className="grid gap-6 lg:grid-cols-3">
          <div className="rounded-[2rem] border border-white/5 bg-white/[0.02] p-8">
            <div className="mb-4 flex items-center gap-3">
              <Terminal size={20} className="text-sky-400" />
              <h3 className="font-bold text-white">Install</h3>
            </div>
            <code className="block rounded-lg bg-black/40 px-4 py-3 font-mono text-sm text-sky-400">
              cd aartiq-browser<br />npm install
            </code>
          </div>
          <div className="rounded-[2rem] border border-white/5 bg-white/[0.02] p-8">
            <div className="mb-4 flex items-center gap-3">
              <FlaskConical size={20} className="text-purple-400" />
              <h3 className="font-bold text-white">Run full suite</h3>
            </div>
            <code className="block rounded-lg bg-black/40 px-4 py-3 font-mono text-sm text-purple-400">
              npx jest
            </code>
          </div>
          <div className="rounded-[2rem] border border-white/5 bg-white/[0.02] p-8">
            <div className="mb-4 flex items-center gap-3">
              <FileText size={20} className="text-emerald-400" />
              <h3 className="font-bold text-white">Run one suite</h3>
            </div>
            <code className="block rounded-lg bg-black/40 px-4 py-3 font-mono text-sm text-emerald-400">
              npx jest tests/sandbox-security.test.js
            </code>
          </div>
        </div>

        <div className="mt-10 flex flex-wrap items-center gap-4">
          <a
            href="https://github.com/Latestinssan/Aartiq/tree/main/aartiq-browser/tests"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-3 rounded-full bg-white px-8 py-4 text-sm font-black uppercase tracking-wider text-black transition hover:bg-sky-400 hover:text-white"
          >
            <ExternalLink size={18} />
            View Test Sources
          </a>
          <Link
            href="/docs/security"
            className="inline-flex items-center gap-3 rounded-full border border-white/10 bg-white/5 px-8 py-4 text-sm font-black uppercase tracking-wider text-white/60 transition hover:bg-white/10 hover:text-white"
          >
            <Layers size={18} />
            Security Model
            <ArrowRight size={16} />
          </Link>
        </div>
      </motion.section>
    </div>
  );
}
