"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import {
  TestTube,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  Terminal,
  FileText,
  BarChart3,
  FlaskConical,
  Bug,
  Activity,
  ArrowRight,
  Layers,
  Cpu,
  ExternalLink
} from "lucide-react";

import {
  tests,
  derived,
  ci,
  security,
} from "@/data/facts";

/**
 * What each suite verifies — written by hand.
 *
 * The COUNTS are deliberately absent here. They come from tests.perSuite, which is
 * generated by `npm run docs:test-facts` from a real jest run, because the old
 * hand-typed table listed only 17 of the 26 suites and its totals did not add up
 * to the declared count.
 */
const suiteFocus: Record<string, string> = {
  "sandbox-security": "Fail-closed sandboxing (Seatbelt / bubblewrap / AppContainer + Job Objects), macOS adversarial OS-enforcement (AF_UNIX + signal confinement), command tokenizer, env sanitization",
  "windows-job-sandbox": "Windows AppContainer JS contract + runtime matrix (suspended AppContainer start, OS-enforced ACL allowlist, verified job, grandchild containment, secret isolation, KILL_ON_JOB_CLOSE)",
  "linux-bwrap-sandbox": "bubblewrap arg generation, namespace/unshare flags (pid/net/ipc/uts/user/cgroup), capability pre-flight fail-closed, Linux runtime enforcement",
  "security-fixes": "Regression suite for applied security fixes",
  "security-validator": "Blocklist / injection detection / risk classification",
  "directory-allowlist": "Path canonicalization, symlink traversal, read/write separation",
  "approval-ticket-security": "Ticket-based approval + capability-controller regression (audit findings)",
  "skill-loading": "Dynamic skill loading, validation allowlist, require-path resolution",
  extraction: "Web extractor, DOM parsing, content extraction edge cases (declared test blocks; it.each expands case count)",
  "tab-intelligence": "Tab intelligence, domain grouping, smart icons",
  "dom-engine": "DOM interaction engine, click/fill strategies",
  "component-tests": "React component behavior and props",
  "webauthn-service": "WebAuthn / FIDO2 challenge-response flow",
  automation: "OS automation layer (click / scroll / app launch)",
  "dom-handlers": "Browser DOM IPC handlers",
  "home-intelligence": "Home intelligence logic",
  "extensions.crx-verifier":
    "CRX3 signature enforcement — deliberately SKIPPED: verifyCrx() wedges the Node 24 OpenSSL verifier on CRX3 header parsing, which previously hung jest until the job timeout. Counted as skipped, never as passing, until the verifier is fixed. See Known Limits.",
  "extensions.permission-analyzer": "Chrome extension manifest permission analysis",
  "guardrails.origin-guard": "Origin trust levels and verb-scoped permission gates",
  "guardrails.prompt-injection": "Prompt-injection detection guards",
  "agent-api.registry": "Agent API tool registry and call routing",
  "agent.tab-lock": "Per-tab locking between concurrent agents",
  "agent.trust": "Agent trust-level assignment and scoping",
  "autofill.vault": "Encrypted autofill vault (AES-GCM, passphrase-derived key)",
  "theme": "Theme and UI-mode switching",
  snapshot: "Snapshot / accessibility-tree reference stability",
  "shell-command-tiers": "Shell tier invariants: destructive pattern floors, unknown binaries, URL arguments, blocked-command rejection, Allow Always eligibility, command key normalization",
  "shell-approval-defaults": "Startup store contents, denials by risk tier, prompting rules, exact-match Always grants, MCP classifier parity, fail-closed fallbacks, legacy grant migration",
  "research-pipeline": "Budget normalization, domain and date parsing, claim extraction, corroboration and dispute logic, recency selection, run events, hard budget enforcement",
  "page-scripts-forms": "Stale ref failures, fill and type semantics, per-field form results, gated form submission, element actions, read-only CSS and prose search",
  "local-server-auth": "Bind host resolution, token extraction precedence, Host and Origin checks, request gate rejections, loopback bridge sockets, MCP pairing URL flow",
  "docs-platform-integration-match-source": "Docs gate: platform action reachability, undelivered scheme handling, IPC channel registration, dropped features and shortcut ids claims pinned to source",
  "agent-api-bridge-tools": "Bridge ref resolution and staleness, snapshot options, page reading tools, navigation stamp reset, search delegation, tool descriptors, fill versus submit gating",
  "web-search-service": "Provider key resolution and fallback order, result count clamps, keyed versus scraped labeling, news provider routing, result parsing, key-safe provider info",
  "apple-intelligence-genmoji": "Genmoji export identity, single-command spawn with JSON prompt transport, off-macOS refusal, IPC channel exposure, helper OS floors, docs command coverage",
  "research-progress-plumbing": "Job reducer transitions, progress clamping and step handling, terminal failure stages, event filtering, main and preload wiring, superseded job filtering",
  "snapshot-ref-binding": "axId stamping and marker cleanup, ref lifecycle and staleness, structural node refusal, single-page search filters, limits and miss behavior",
  "file-paths": "URL versus file path detection, path wrapping preprocessing, tokenizer classification, code block protection, idempotence, rendered link and chip output",
  "docs-deep-links-match-source": "Docs gate: deep-link command statuses, dead command reachability, documented parameters, retired route and mechanism claims pinned to source",
  "docs-sync-match-source": "Docs gate: Cloud Sync trust levels, discovery mechanism, size and duration limits, feature capabilities and encryption scoping claims pinned to source",
  "sensitive-paths-deny": "Sensitive-path denial over allowlisted homes and workspaces, symlink realpath resolution, read-only directory defaults, broad grant narrowing, sandbox deny blocks",
  "sync-auth-tokens": "Pairing token issuance, listener authentication and lifetime checks, refresh device binding, unpair revocation, pairing lockout, HTTP token and Host validation",
  "cloud-sync-error-surface": "Rejected cloud write logging and error emission across source and compiled twins, failure forwarding to renderer, status line surfacing, success silence",
  "docs-listener-claims-match-source": "Docs gate: listener binding, token coverage, approval tier tables, enforcement layer and tool count claims pinned to source",
  "allow-always-lifetime": "Grant lifetime policy constant, grant record persistence and revocation, gate lifetime enforcement and sweeping, pre-lifetime grant migration",
  "permission-store-system-root": "System root rejection in allowed directories, trailing slash handling, exact-match path boundary rule, normal directory acceptance, rejection auditing",
  "approval-gate-concurrency": "Ticket single redemption under concurrency, sequential replay refusal, input hash burning, scope mismatch and status reporting, live redemption path",
  "wifi-sync-upgrade": "WebSocket upgrade Origin and Host gating, DNS rebinding and foreign origin refusal over real sockets, access token gating of unpair",
  "network-listener-hardening": "Loopback-only binding for bridge and services, wildcard-free listen calls, distinct default ports across agent API and native bridge, routing targets",
  "remote-shell-approval": "Remote origin shell approval registration policy, QR and PIN ticket flow, invalid and tampered input denial, single use redemption, sandbox fallback",
  "native-bridge-permissions": "Permission grant, revoke and read routes, immediate gate visibility, lost-update resistance, invalid level fail-closed handling, audit trail",
  "session-token": "Per-listener token file creation and mode, cross-restart persistence, listener separation, corrupt file replacement, unwritable home fallback, rotation",
  "citation-links": "Citation bracket to markdown link normalization, verbatim URL copying, idempotence, rendered href correctness, plain text and bracket preservation",
  "docs-shortcuts-match-source": "Docs gate: published shortcut table, registered accelerator parity, duplicate and unbound entries, scoped key descriptions and conflict surfacing claims pinned to source",
  "native-approval-biometrics": "Dialog label honesty, deny handling, biometric flag enforcement with fail-closed verification and unsupported platforms, per session caching",
  "licence-audit-rename": "Root licence text, manifest and installer licence declaration, persisted audit file rename migration without clobbering, chat export default naming",
  "linux-ipc-registration": "Linux bridge channel registration uniqueness against main, preload invoked channel ownership, platform guard error objects on non-Linux",
  "pairing-auth": "Deterministic master key signature computation and verification, wrong key and tampered signature rejection, fail-closed missing inputs, replay window",
  "sync-handlers-window": "Live window resolution for prompt delivery, honest failure when windows are gone, destroyed window safety, captured window fallback, windowless status",
  "wifi-sync-pairing": "Pairing code stability across restarts, unknown device code checks, paired device id recognition with trusted legacy ids, untrusted legacy rejection",
  "benchmark-smoke": "Benchmark runner completion, expected benchmark presence and timing shape, environment capture, KDF work floors, unknown only flag rejection",
  "local-server-auth-lockout": "Remote address failure counting and lockout, lock clearing on success, shared address family counters, loopback exemption, socketless local handling",
  "ai-command-parser-plan": "PLAN and THINK payload field extraction, bracket form parsing, reasoning note capture so plan and thinking text stays populated",
  "approval-gate": "Approval ticket race prevention, one-time consumption, sequential replay refusal, mismatched input burning",
  "markdown-render": "Currency text kept literal in chat markdown, dollar amounts preserved across sentences, double dollar math still rendered",
};

const testSuites = tests.perSuite.map((s) => ({
  file: s.suite,
  count: s.declared,
  passed: s.passed,
  skipped: s.skipped,
  focus: suiteFocus[s.suite] ?? "—",
}));

const crxSkip = tests.skipBreakdown.find((b) => b.reason.includes("CRX3"))?.count ?? 0;
const regressionCount =
  testSuites.find((s) => s.file === "security-fixes")?.count ?? 0;

const ciTotals = ci.perJob.reduce(
  (acc, j) => ({
    passed: acc.passed + j.passed,
    skipped: acc.skipped + j.skipped,
    failed: acc.failed + j.failed,
    declared: acc.declared + j.declared,
  }),
  { passed: 0, skipped: 0, failed: 0, declared: 0 }
);

const covered = [
  "Fail-closed by construction: every sandbox setup, validation, or policy failure returns a structured SANDBOX_* error and the command is never silently run unsandboxed — there is no automatic fallback path",
  "macOS Seatbelt — real OS enforcement: writing outside the directory allowlist is denied by the kernel and the file is verified absent; reading a secret outside the allowlist is denied; /tmp is writable; an IP network bind is denied; an AF_UNIX socket bind is denied; signalling a host process is denied while self-signal works; reading/writing through a symlink that escapes the allowlist is denied; a child process spawned by the target is still contained",
  "Linux bubblewrap — closed-by-default namespaces (pid/net/ipc/uts/user/cgroup + new session), correct --bind (write) vs --ro-bind (read-only) mapping, network denied by default, and fail-closed when bwrap is missing OR present-but-incapable of creating the required namespaces (the capability pre-flight)",
  "Windows AppContainer — policy fail-closed (missing runner, invalid allowlist, network-allowlist requests), result parsing, explicit isolation flags ({ filesystem:true, network:true, process:true }), plus a runtime matrix proving suspended AppContainer start + OS-enforced ACL allowlist + verified job assignment + grandchild containment + secret isolation + KILL_ON_JOB_CLOSE",
  "Explicit isolation contract — every result carries { filesystem, network, process }; macOS/Linux/Windows all report all-true when their platform sandbox is active, and any setup failure or unsandboxed run reports all-false",
  "Directory allowlist — fs.realpath() canonicalization, ../ traversal, symlink escape, read-only vs read-write separation, and invalid/missing-path rejection (never silently skipped)",
  "Command execution — the tokenizer preserves quoted arguments verbatim, separates direct execution from explicit shell mode, and never reconstructs a command via a string-joined sh -c; it is documented as a classifier, not a security parser",
  "Environment sanitization — API keys, tokens, and secrets are stripped from every sandboxed process; only an allowlisted set of non-credential variables passes through",
  `Security regressions — a ${regressionCount}-test regression suite re-verifying each applied security fix, plus approval-ticket tests that lock in the audit remediation`,
];

/**
 * Every sentence in here that contains a number is assembled from `ci` /
 * `tests` at render time. The prose around them (what the tests actually
 * verify, and what they don't) is hand-written and stays hand-written.
 */
const limitations = [
  `Runtime enforcement tests only EXECUTE on their own OS. ${ci.jobs.detail} Latest run [#${ci.latestRun.runNumber}](${ci.latestRun.url}) (${
    ci.latestRun.event
  }, ${ci.latestRun.date}) reported: ${ci.perJob
    .map(
      (j) =>
        `${j.name} on ${j.os} ${j.passed} passed / ${j.skipped} skipped / ${j.failed} failed of ${j.declared}`,
    )
    .join("; ")}. Suspended AppContainer start, OS-enforced ACL allowlist, verified job assignment, grandchild containment, secret isolation, and KILL_ON_JOB_CLOSE all return verified sandbox results.`,
  `The extensions.crx-verifier suite (${crxSkip} tests) is deliberately SKIPPED in CI: verifyCrx() trips a Node 24 OpenSSL decode path (ERR_OSSL_UNSUPPORTED / an event-loop-blocking native call) while parsing the CRX3 header, which previously hung the jest job until the ${ci.jobs.timeout} It is not counted as passing — it stays visible as a skipped suite (${crxSkip} skipped in the totals above) until the verifier's header parsing is fixed and the suite is re-enabled.`,
  "macOS Seatbelt OS-enforcement tests execute only on macOS; they pass on this machine and run in CI on macos-latest. The profile-generation and fail-closed config paths are asserted on every platform.",
  "These are unit and integration tests for core modules. They do NOT cover the full Electron UI, installers, MSIX/MSI packaging, or complete end-to-end user flows.",
  "A sandbox confines what code can do; it is not a proof that the AI's decisions are safe, nor a substitute for least-privilege OS accounts, patched dependencies, or simply not running untrusted code. See the security page's 'What this does NOT guarantee'.",
  `Counts above are declared it()/test() blocks as of ${derived.testGeneratedAt.slice(0, 10)} on ${derived.testEnvironment}; suites using it.each expand into more executed cases. Run npx jest (Node 24+, some deps are ESM) or check the CI run for jest.yml for exact pass/skip/fail numbers.`,
];

export default function TestingPage() {
  return (
    <div className="space-y-24">
      {/* Hero */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/5 px-5 py-2">
          <TestTube size={14} className="text-emerald-400" />
          <span className="text-[10px] font-black uppercase tracking-[0.4em] text-emerald-400">
            Testing &amp; Test Series
          </span>
        </div>

        <h1 className="mb-8 text-5xl font-black uppercase tracking-tighter sm:text-7xl">
          Test <span className="text-white/20">Series</span>
        </h1>

        <p className="max-w-3xl text-xl font-medium leading-relaxed text-white/50">
          Aartiq&apos;s core modules are verified with an automated Jest test suite. This page reports
          the real numbers, what is covered, and what is not.
        </p>

        {/* Stats — every figure below is imported from the generated test facts. */}
        <div className="mt-12 grid gap-6 sm:grid-cols-4">
          <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-6 text-center">
            <BarChart3 size={32} className="mx-auto mb-4 text-emerald-400" />
            <h3 className="text-3xl font-black text-emerald-400">{tests.suites.total}</h3>
            <p className="text-sm text-white/50">
              Test Suites ({tests.suites.passed} passing + {tests.suites.skipped} skipped)
            </p>
          </div>
          <div className="rounded-2xl border border-sky-500/20 bg-sky-500/5 p-6 text-center">
            <Layers size={32} className="mx-auto mb-4 text-sky-400" />
            <h3 className="text-3xl font-black text-sky-400">{tests.tests.declared}</h3>
            <p className="text-sm text-white/50">Total Tests (declared blocks)</p>
          </div>
          <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-6 text-center">
            <CheckCircle2 size={32} className="mx-auto mb-4 text-emerald-400" />
            <h3 className="text-3xl font-black text-emerald-400">{tests.tests.passed}</h3>
            <p className="text-sm text-white/50">Passing</p>
          </div>
          <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-6 text-center">
            <Activity size={32} className="mx-auto mb-4 text-amber-400" />
            <h3 className="text-3xl font-black text-amber-400">{tests.tests.skipped}</h3>
            <p className="text-sm text-white/50">
              Skipped · {tests.tests.failed} failing
            </p>
          </div>
        </div>

        <p className="mt-3 text-xs text-white/30">
          Counts generated on {derived.testEnvironment} at {derived.testGeneratedAt} — not typed.
          CI runs a different platform, so its per-job numbers differ; see the run below.
        </p>

        <a
          href={ci.latestRun.url}
          target="_blank"
          rel="noopener noreferrer"
          className="mt-8 inline-flex items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-5 py-2.5 text-sm font-bold text-emerald-300 transition-colors hover:bg-emerald-500/20"
        >
          <ShieldCheck size={16} />
          {ci.jobs.defined}/{ci.jobs.defined} jobs {ci.latestRun.conclusion} — run #
          {ci.latestRun.runNumber} ({ci.latestRun.event}, {ci.latestRun.date})
          <ExternalLink size={16} />
        </a>
      </motion.section>

      {/* Per-suite breakdown */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
      >
        <div className="mb-16">
          <p className="mb-4 text-[10px] font-black uppercase tracking-[0.5em] text-white/20">
            Breakdown
          </p>
          <h2 className="text-4xl font-black uppercase tracking-tighter sm:text-5xl">
            Test <span className="text-white/20">Suites</span>
          </h2>
        </div>

        <div className="overflow-hidden rounded-[2rem] border border-white/5 bg-white/[0.02]">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-white/5 text-[10px] font-black uppercase tracking-[0.3em] text-white/30">
                <th className="px-6 py-4">Suite</th>
                <th className="px-6 py-4">Tests</th>
                <th className="hidden px-6 py-4 md:table-cell">What it verifies</th>
              </tr>
            </thead>
            <tbody>
              {testSuites.map((s, i) => (
                <tr
                  key={s.file}
                  className={`border-b border-white/5 transition hover:bg-white/[0.02] ${
                    i === testSuites.length - 1 ? "border-b-0" : ""
                  }`}
                >
                  <td className="px-6 py-4 font-mono text-sm text-sky-400">{s.file}</td>
                  <td className="px-6 py-4">
                    <span className="inline-flex items-center gap-2 rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-bold text-emerald-400">
                      {s.count}
                    </span>
                    {s.skipped > 0 && (
                      <span className="ml-2 inline-flex items-center gap-1 rounded-full bg-amber-500/10 px-3 py-1 text-xs font-bold text-amber-400">
                        {s.skipped} skipped
                      </span>
                    )}
                  </td>
                  <td className="hidden px-6 py-4 text-sm text-white/50 md:table-cell">{s.focus}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </motion.section>

      {/* Latest CI run */}
      <motion.section
        id="ci-run"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.15 }}
      >
        <div className="mb-16">
          <p className="mb-4 text-[10px] font-black uppercase tracking-[0.5em] text-white/20">
            Continuous Integration
          </p>
          <h2 className="text-4xl font-black uppercase tracking-tighter sm:text-5xl">
            Latest <span className="text-white/20">CI Run</span>
          </h2>
          <p className="mt-6 max-w-3xl text-sm text-white/40">
            {ci.jobs.detail} The run below is{" "}
            <a
              href={ci.latestRun.url}
              target="_blank"
              rel="noopener noreferrer"
              className="font-bold text-emerald-300 hover:text-emerald-200"
            >
              #{ci.latestRun.runNumber}
            </a>{" "}
            ({ci.latestRun.event}, {ci.latestRun.date}, conclusion: {ci.latestRun.conclusion}).
          </p>
        </div>

        <div className="overflow-hidden rounded-[2rem] border border-white/5 bg-white/[0.02]">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-white/5 text-[10px] font-black uppercase tracking-[0.3em] text-white/30">
                <th className="px-6 py-4">Job</th>
                <th className="px-6 py-4">OS</th>
                <th className="px-6 py-4">Passed</th>
                <th className="px-6 py-4">Skipped</th>
                <th className="px-6 py-4">Failed</th>
                <th className="px-6 py-4">Declared</th>
              </tr>
            </thead>
            <tbody className="text-sm">
              {ci.perJob.map((j) => (
                <tr key={j.name} className="border-b border-white/5 transition hover:bg-white/[0.02]">
                  <td className="px-6 py-4 font-mono text-xs text-sky-400">{j.name}</td>
                  <td className="px-6 py-4 text-xs text-white/50">{j.os}</td>
                  <td className="px-6 py-4 font-bold text-emerald-400">{j.passed}</td>
                  <td className="px-6 py-4 text-amber-400">{j.skipped}</td>
                  <td className="px-6 py-4 text-white/50">{j.failed}</td>
                  <td className="px-6 py-4 text-white/50">{j.declared}</td>
                </tr>
              ))}
              <tr className="border-t border-white/10 text-xs font-black uppercase tracking-wider">
                <td className="px-6 py-4 text-white/40" colSpan={2}>
                  All {ci.jobs.defined} jobs
                </td>
                <td className="px-6 py-4 text-emerald-400">{ciTotals.passed}</td>
                <td className="px-6 py-4 text-amber-400">{ciTotals.skipped}</td>
                <td className="px-6 py-4 text-white/50">{ciTotals.failed}</td>
                <td className="px-6 py-4 text-white/50">{ciTotals.declared}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="mt-6 overflow-hidden rounded-[2rem] border border-white/5 bg-white/[0.02]">
          <div className="border-b border-white/5 px-6 py-4">
            <h3 className="text-sm font-black uppercase tracking-wider text-white">Why tests are skipped</h3>
            <p className="mt-1 text-xs text-white/40">
              Breakdown from the generated test facts ({derived.testGeneratedAt.slice(0, 10)}): {tests.tests.skipped} skipped in total.
            </p>
          </div>
          <table className="w-full text-left">
            <tbody className="text-sm">
              {tests.skipBreakdown.map((b) => (
                <tr key={b.reason} className="border-b border-white/5 last:border-b-0">
                  <td className="px-6 py-3 text-white/60">{b.reason}</td>
                  <td className="px-6 py-3 text-right font-mono text-xs text-amber-400">{b.count}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </motion.section>

      {/* What's covered */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <div className="mb-16">
          <p className="mb-4 text-[10px] font-black uppercase tracking-[0.5em] text-white/20">
            Coverage
          </p>
          <h2 className="text-4xl font-black uppercase tracking-tighter sm:text-5xl">
            What&apos;s <span className="text-white/20">Covered</span>
          </h2>
        </div>

        <div className="rounded-[2rem] border border-emerald-500/20 bg-emerald-500/5 p-10">
          <ul className="space-y-4">
            {covered.map((item, i) => (
              <li key={i} className="flex items-start gap-4 text-sm text-white/60">
                <CheckCircle2 size={18} className="mt-0.5 shrink-0 text-emerald-400" />
                {item}
              </li>
            ))}
          </ul>
        </div>
      </motion.section>

      {/* Known limits */}
      <motion.section
        id="known-limits"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
      >
        <div className="mb-16">
          <p className="mb-4 text-[10px] font-black uppercase tracking-[0.5em] text-white/20">
            Coverage Boundaries
          </p>
          <h2 className="text-4xl font-black uppercase tracking-tighter sm:text-5xl">
            Known <span className="text-amber-400">Limits</span>
          </h2>
        </div>

        <div className="rounded-[2rem] border border-amber-500/20 bg-amber-500/5 p-10">
          <div className="mb-8 flex items-center gap-4">
            <AlertTriangle size={40} className="text-amber-400" />
            <div>
              <h3 className="text-xl font-black uppercase tracking-wider">
                What this suite does NOT prove
              </h3>
              <p className="text-sm text-white/50">
                We would rather state these limits plainly than overstate coverage.
              </p>
            </div>
          </div>

          <ul className="space-y-4">
            {limitations.map((item, i) => (
              <li key={i} className="flex items-start gap-4 text-sm text-white/60">
                <AlertTriangle size={18} className="mt-0.5 shrink-0 text-amber-400" />
                {item}
              </li>
            ))}
          </ul>
        </div>

        <div className="mt-6 rounded-[2rem] border border-white/5 bg-white/[0.02] p-10">
          <div className="mb-6 flex items-center gap-4">
            <AlertTriangle size={32} className="text-amber-400/70" />
            <div>
              <h3 className="text-xl font-black uppercase tracking-wider">
                Known limits in the product
              </h3>
              <p className="text-sm text-white/50">
                The shared list kept in the source of truth that also renders in the repository
                README — product-wide, not just this suite.
              </p>
            </div>
          </div>
          <ul className="space-y-3">
            {security.knownLimits.map((limit, i) => (
              <li key={i} className="flex items-start gap-3 text-sm text-white/60">
                <AlertTriangle size={16} className="mt-0.5 shrink-0 text-amber-400/70" />
                {limit}
              </li>
            ))}
          </ul>
        </div>
      </motion.section>

      {/* Run the tests */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
      >
        <div className="mb-16">
          <p className="mb-4 text-[10px] font-black uppercase tracking-[0.5em] text-white/20">
            Reproduce
          </p>
          <h2 className="text-4xl font-black uppercase tracking-tighter sm:text-5xl">
            Run the <span className="text-white/20">Tests</span>
          </h2>
        </div>

        <div className="grid gap-6 lg:grid-cols-3">
          <div className="rounded-[2rem] border border-white/5 bg-white/[0.02] p-8">
            <div className="mb-4 flex items-center gap-3">
              <Terminal size={20} className="text-sky-400" />
              <h3 className="font-bold text-white">Install</h3>
            </div>
            <code className="block rounded-lg bg-black/40 px-4 py-3 font-mono text-sm text-sky-400">
              cd aartiq-browser<br />npm install
            </code>
          </div>
          <div className="rounded-[2rem] border border-white/5 bg-white/[0.02] p-8">
            <div className="mb-4 flex items-center gap-3">
              <FlaskConical size={20} className="text-purple-400" />
              <h3 className="font-bold text-white">Run full suite</h3>
            </div>
            <code className="block rounded-lg bg-black/40 px-4 py-3 font-mono text-sm text-purple-400">
              npx jest
            </code>
          </div>
          <div className="rounded-[2rem] border border-white/5 bg-white/[0.02] p-8">
            <div className="mb-4 flex items-center gap-3">
              <FileText size={20} className="text-emerald-400" />
              <h3 className="font-bold text-white">Run one suite</h3>
            </div>
            <code className="block rounded-lg bg-black/40 px-4 py-3 font-mono text-sm text-emerald-400">
              npx jest tests/sandbox-security.test.js
            </code>
          </div>
        </div>

        <div className="mt-10 flex flex-wrap items-center gap-4">
          <a
            href="https://github.com/Latestinssan/Aartiq/tree/main/aartiq-browser/tests"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-3 rounded-full bg-white px-8 py-4 text-sm font-black uppercase tracking-wider text-black transition hover:bg-sky-400 hover:text-white"
          >
            <ExternalLink size={18} />
            View Test Sources
          </a>
          <Link
            href="/docs/security"
            className="inline-flex items-center gap-3 rounded-full border border-white/10 bg-white/5 px-8 py-4 text-sm font-black uppercase tracking-wider text-white/60 transition hover:bg-white/10 hover:text-white"
          >
            <Layers size={18} />
            Security Model
            <ArrowRight size={16} />
          </Link>
        </div>
      </motion.section>
    </div>
  );
}
