"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import componentData from "@/data/component-data.json";
import {
  curatedDescriptions,
  desktopMembership,
  flutterMembership,
  serviceOrder,
} from "@/data/component-curation";
import { 
  Bot, 
  Shield, 
  Zap, 
  Globe,
  Terminal,
  Smartphone,
  FileText,
  Layers,
  Cloud,
  Wifi,
  Bell,
  Calendar,
  Monitor,
  Command,
  Lock,
  Eye,
  MousePointer,
  Search,
  Code2,
  Database,
  Settings,
  Share2,
  Printer,
  Volume2,
  HardDrive,
  Cpu,
  Activity,
  ArrowRight,
  Link2,
  LayoutGrid,
  Package,
  Puzzle,
  Server,
  Key,
  Keyboard,
  Brush,
  Plug,
  MonitorSmartphone,
  Play,
  Pause,
  Trash2,
  CheckCircle2,
  AlertCircle,
  Timer,
  Workflow,
  Download,
  Upload,
  Send,
  History,
  Moon,
  Sun,
  Github,
  ExternalLink,
  ChevronDown,
  ChevronRight,
  Box,
  FolderTree,
  GitBranch,
  Layers3,
  AppWindow,
  Settings2,
  Users,
  Webhook,
  RefreshCw,
  Apple,
  type LucideIcon
} from "lucide-react";

interface ComponentEntry {
  name: string;
  lines?: number;
  description: string;
  path?: string;
  tags?: string[];
}

interface CategorySection {
  title: string;
  icon: LucideIcon;
  color: string;
  borderColor: string;
  iconColor: string;
  components: ComponentEntry[];
  description?: string;
  /** Render collapsed by default (the uncurated backlog bucket). */
  defaultCollapsed?: boolean;
}

// ---------------------------------------------------------------------------
// Inventory source: every component below is read from
// src/data/component-data.json (generated by aartiq-browser/scripts/
// component-scanner.js). Curated category placement, display order and
// hand-written blurbs live in src/data/component-curation.ts. Files the scan
// does not contain never render; files it adds render under "Uncurated Scan
// Output" until someone curates them.
// ---------------------------------------------------------------------------

interface ScanComponent {
  name: string;
  path: string;
  lines: number;
  description: string;
  tags: string[];
  group?: string;
}

type CategoryMeta = Omit<CategorySection, "components">;

const scan = componentData as unknown as {
  generated: string;
  version: string;
  desktop: { total: number; totalLines: number; components: ScanComponent[] };
  flutter: { total: number; totalLines: number; components: ScanComponent[] };
  summary: { total: number; totalLines: number };
};

/** Bucket for scanned files nobody has curated yet — listed last, collapsed. */
const UNCATEGORIZED_META: CategoryMeta = {
  title: "Uncurated Scan Output",
  icon: FolderTree,
  description:
    "Found by the latest scan but not yet curated — place files via src/data/component-curation.ts",
  color: "from-slate-500/20 to-white/5",
  borderColor: "border-white/10",
  iconColor: "text-white/50",
  defaultCollapsed: true,
};

const DESKTOP_META: CategoryMeta[] = [
] = [
  {
    title: "AI & Chat",
    icon: Bot,
    description: "AI chat, command processing, conversation management",
    color: "from-blue-500/20 to-cyan-500/20",
    borderColor: "border-blue-500/20",
    iconColor: "text-blue-400",
  },
  {
    title: "Settings & Configuration",
    icon: Settings,
    description: "Settings panels: LLM, automation, sync, permissions, plugins",
    color: "from-emerald-500/20 to-teal-500/20",
    borderColor: "border-emerald-500/20",
    iconColor: "text-emerald-400",
  },
  {
    title: "Browser Core",
    icon: Globe,
    description: "WebView container, tab management, navigation UI",
    color: "from-amber-500/20 to-orange-500/20",
    borderColor: "border-amber-500/20",
    iconColor: "text-amber-400",
  },
  {
    title: "Automation & Tasks",
    icon: Terminal,
    description: "OS automation service: mouse, keyboard, OCR, scheduling",
    color: "from-purple-500/20 to-pink-500/20",
    borderColor: "border-purple-500/20",
    iconColor: "text-purple-400",
  },
  {
    title: "PDF & Documents",
    icon: FileText,
    description: "PDF generation, editing, template parsing, document export",
    color: "from-indigo-500/20 to-violet-500/20",
    borderColor: "border-indigo-500/20",
    iconColor: "text-indigo-400",
  },
  {
    title: "Mobile & Sync",
    icon: Smartphone,
    description: "Flutter mobile app, WebSocket sync, P2P file transfer",
    color: "from-pink-500/20 to-rose-500/20",
    borderColor: "border-pink-500/20",
    iconColor: "text-pink-400",
  },
  {
    title: "LLM Providers",
    icon: Cpu,
    description: "LLM providers: OpenAI, Claude, Gemini, Groq, Ollama",
    color: "from-cyan-500/20 to-blue-500/20",
    borderColor: "border-cyan-500/20",
    iconColor: "text-cyan-400",
  },
  {
    title: "Native macOS UI",
    icon: Monitor,
    description: "SwiftUI panels: theme, settings, menu, diagrams",
    color: "from-sky-500/20 to-blue-500/20",
    borderColor: "border-sky-500/20",
    iconColor: "text-sky-400",
  },
  {
    title: "Integrations & Services",
    icon: Plug,
    description: "Integrations: Gmail, RAG, web search, voice, MCP, Firebase",
    color: "from-amber-500/20 to-orange-500/20",
    borderColor: "border-amber-500/20",
    iconColor: "text-amber-400",
  },
  {
    title: "Extensibility",
    icon: Puzzle,
    description: "Plugin system, extensions, deep link handler, marketplace",
    color: "from-cyan-500/20 to-teal-500/20",
    borderColor: "border-cyan-500/20",
    iconColor: "text-cyan-400",
  },
  {
    title: "Core Architecture",
    icon: Box,
    description: "Core: main process, security, command parser, platform bridges",
    color: "from-violet-500/20 to-purple-500/20",
    borderColor: "border-violet-500/20",
    iconColor: "text-violet-400",
  },
  {
    title: "Dashboards & Studios",
    icon: LayoutGrid,
    description: "Dashboards: admin, coding, studio, media, documentation",
    color: "from-violet-500/20 to-purple-500/20",
    borderColor: "border-violet-500/20",
    iconColor: "text-violet-400",
  },
  {
    title: "Utilities & Entertainment",
    icon: Box,
    description: "Utilities: games, password manager, shopping cart, navigation",
    color: "from-rose-500/20 to-red-500/20",
    borderColor: "border-rose-500/20",
    iconColor: "text-rose-400",
  },
  UNCATEGORIZED_META,
];

const FLUTTER_META: CategoryMeta[] = [
] = [
  {
    title: "Core Pages",
    icon: AppWindow,
    description: "Main screens: desktop control, agent chat, home, settings",
    color: "from-blue-500/20 to-cyan-500/20",
    borderColor: "border-blue-500/20",
    iconColor: "text-blue-400",
  },
  {
    title: "Core Services",
    icon: Server,
    description: "Services: sync, agent, browser controller, WebView tab",
    color: "from-emerald-500/20 to-teal-500/20",
    borderColor: "border-emerald-500/20",
    iconColor: "text-emerald-400",
  },
  {
    title: "Data Models",
    icon: Database,
    description: "Models: browser state, WebView state, window, favorites",
    color: "from-amber-500/20 to-orange-500/20",
    borderColor: "border-amber-500/20",
    iconColor: "text-amber-400",
  },
  {
    title: "App Bar Components",
    icon: Settings2,
    description: "App bars: tab toolbar, desktop toolbar, certificate info",
    color: "from-purple-500/20 to-pink-500/20",
    borderColor: "border-purple-500/20",
    iconColor: "text-purple-400",
  },
  {
    title: "Developer Tools",
    icon: Code2,
    description: "Dev tools: storage manager, network info, JS console",
    color: "from-indigo-500/20 to-violet-500/20",
    borderColor: "border-indigo-500/20",
    iconColor: "text-indigo-400",
  },
  {
    title: "Settings Pages",
    icon: Settings,
    description: "Settings: Android, iOS, cross-platform, settings hub",
    color: "from-pink-500/20 to-rose-500/20",
    borderColor: "border-pink-500/20",
    iconColor: "text-pink-400",
  },
  {
    title: "UI Components",
    icon: LayoutGrid,
    description: "Widgets: tab viewer, dialogs, images, animations",
    color: "from-cyan-500/20 to-teal-500/20",
    borderColor: "border-cyan-500/20",
    iconColor: "text-cyan-400",
  },
  UNCATEGORIZED_META,
];

function toEntry(c: ScanComponent): ComponentEntry {
  return {
    name: c.name,
    path: c.path,
    lines: c.lines,
    description: curatedDescriptions[c.name] ?? c.description,
    tags: c.tags,
  };
}

/**
 * Place every scanned component: curated membership first (dropping entries the
 * scan no longer contains), everything else into the trailing "Uncurated Scan
 * Output" category. Entries in the `service` group are left out — they belong
 * to the background-service tab unless a curated category claimed them.
 */
function buildCategories(
  metas: CategoryMeta[],
  membership: Record<string, string[]>,
  pool: ScanComponent[]
): { categories: CategorySection[]; claimed: Set<string> } {
  const categories: CategorySection[] = metas.map((meta) => ({ ...meta, components: [] }));
  const byName = new Map<string, ScanComponent>();
  for (const c of pool) if (!byName.has(c.name)) byName.set(c.name, c);

  const claimed = new Set<string>();
  for (const [title, names] of Object.entries(membership)) {
    const target = categories.find((k) => k.title === title);
    for (const name of names) {
      const c = byName.get(name);
      if (!c || claimed.has(c.path)) continue;
      claimed.add(c.path);
      target?.components.push(toEntry(c));
    }
  }

  const uncurated = categories[categories.length - 1];
  for (const c of pool) {
    if (claimed.has(c.path) || c.group === "service") continue;
    claimed.add(c.path);
    uncurated.components.push(toEntry(c));
  }
  return { categories, claimed };
}

const desktopBuilt = buildCategories(DESKTOP_META, desktopMembership, scan.desktop.components);
const desktopCategories = desktopBuilt.categories;

const flutterBuilt = buildCategories(FLUTTER_META, flutterMembership, scan.flutter.components);
const flutterCategories = flutterBuilt.categories;

// Background-service tab: curated display order first, then anything else the
// scan found in src/service that no curated desktop category claimed.
const servicePool = scan.desktop.components.filter(
  (c) => c.group === "service" && !desktopBuilt.claimed.has(c.path)
);
const serviceJson = new Map<string, ScanComponent>();
for (const c of servicePool) if (!serviceJson.has(c.name)) serviceJson.set(c.name, c);
const serviceSeen = new Set<string>();
const backgroundServiceComponents: ComponentEntry[] = [];
for (const name of serviceOrder) {
  const c = serviceJson.get(name);
  if (!c || serviceSeen.has(c.path)) continue;
  serviceSeen.add(c.path);
  backgroundServiceComponents.push(toEntry(c));
}
for (const c of servicePool) {
  if (serviceSeen.has(c.path)) continue;
  serviceSeen.add(c.path);
  backgroundServiceComponents.push(toEntry(c));
}

const totalComponents = desktopCategories.reduce((sum, cat) => sum + cat.components.length, 0) +
  flutterCategories.reduce((sum, cat) => sum + cat.components.length, 0) +
  backgroundServiceComponents.length;

const flutterTotal = flutterCategories.reduce((sum, cat) => sum + cat.components.length, 0);
const flutterTotalLines = flutterCategories.reduce((sum, cat) =>
  sum + cat.components.reduce((lineSum, comp) => lineSum + (comp.lines || 0), 0), 0);

const desktopTotal = desktopCategories.reduce((sum, cat) => sum + cat.components.length, 0);
const serviceTotalLines = backgroundServiceComponents.reduce((sum, comp) => sum + (comp.lines || 0), 0);

// ---------------------------------------------------------------------------
// Platform tab — curated content (not scanned): three OS cards + the matrix.
// ---------------------------------------------------------------------------

const platformIntegrations = [
  {
    key: "macos",
    title: "macOS Integration",
    blurb: "Siri Shortcuts, AppleScript, Vision Kit, Voice Control",
    href: "/docs/apple-integration",
    items: [
      "App Intents (12 shortcuts)",
      "URL scheme: aartiq://",
      "Voice: Dictation + TTS",
      "OCR: Vision framework",
      "Click: steve CLI / AXUIElement",
    ],
  },
  {
    key: "windows",
    title: "Windows Integration",
    blurb: "Shortcuts, Voice, Copilot, PowerShell",
    href: "/docs/windows-integration",
    items: [
      "Windows Shortcuts support",
      "Protocol: com.microsoft.copilot:",
      "Voice: System.Speech",
      "OCR: Windows OCR API",
      "Click: xa11y / nut.js",
    ],
  },
  {
    key: "linux",
    title: "Linux Integration",
    blurb: "GNOME, KDE, XFCE, MATE",
    href: "/docs/linux-integration",
    items: [
      "Desktop entries (.desktop)",
      "URL scheme: aartiq://",
      "Voice: espeak (80+ voices)",
      "OCR: AT-SPI2",
      "Click: xdotool",
    ],
  },
];

const automationMatrix = [
  { feature: "Clicking", macos: "steve CLI / AXUIElement", windows: "nut.js / xa11y", linux: "xdotool" },
  { feature: "OCR", macos: "Vision framework", windows: "Windows OCR", linux: "AT-SPI2 + Tesseract" },
  { feature: "TTS", macos: "AVSpeechSynthesizer", windows: "System.Speech", linux: "espeak" },
  { feature: "Voice Input", macos: "Dictation", windows: "System.Speech", linux: "pocketsphinx" },
  { feature: "Shortcuts", macos: "Shortcuts App", windows: "Windows Shortcuts", linux: ".desktop files" },
  { feature: "Protocol", macos: "aartiq://", windows: "aartiq://", linux: "aartiq://" },
];

const integrationsCount =
  platformIntegrations.reduce((sum, p) => sum + p.items.length, 0) + automationMatrix.length;

const PLATFORM_ICON: Record<string, LucideIcon> = { macos: Apple, windows: Monitor, linux: Terminal };

function slugify(str: string) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
}

function ComponentCard({ component, color, borderColor }: { component: ComponentEntry; color: string; borderColor: string }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
    >
      <Link href={`/docs/components/${slugify(component.name)}`}>
        <div className="group block rounded-xl border border-white/5 bg-white/[0.02] p-4 transition-all hover:border-white/10 hover:bg-white/[0.04]">
          <div className="flex items-start justify-between gap-3">
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1">
                <h3 className="font-mono text-sm font-bold text-white group-hover:text-sky-400 transition-colors truncate">
                  {component.name}
                </h3>
                {component.lines && (
                  <span className="shrink-0 rounded bg-white/5 px-1.5 py-0.5 text-[10px] font-mono text-white/30">
                    {component.lines.toLocaleString()} lines
                  </span>
                )}
              </div>
              <p className="text-xs text-white/40 line-clamp-2">{component.description}</p>
              {component.tags && (
                <div className="flex flex-wrap gap-1 mt-2">
                  {component.tags.map((tag) => (
                    <span key={tag} className="rounded bg-white/5 px-1.5 py-0.5 text-[10px] text-white/30">
                      {tag}
                    </span>
                  ))}
                </div>
              )}
            </div>
            {component.path && (
              <ArrowRight size={14} className="shrink-0 mt-1 text-white/20 transition-transform group-hover:translate-x-1 group-hover:text-sky-400" />
            )}
          </div>
        </div>
      </Link>
    </motion.div>
  );
}

function CategorySectionComponent({ category, index }: { category: CategorySection; index: number }) {
  const [isExpanded, setIsExpanded] = useState(!category.defaultCollapsed);
  
  return (
    <motion.section
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05 }}
    >
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="mb-6 flex w-full items-center gap-4 group"
      >
        <div className={`flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br ${category.color} border ${category.borderColor} transition-transform group-hover:scale-105`}>
          <category.icon size={24} className={category.iconColor} />
        </div>
        <div className="flex-1 text-left">
          <p className="text-[10px] font-black uppercase tracking-[0.5em] text-white/30">
            {category.components.length} components
          </p>
          <h2 className="text-xl font-black uppercase tracking-wider flex items-center gap-2">
            {category.title}
            {category.description && (
              <span className="text-sm font-normal text-white/40 normal-case tracking-normal">
                — {category.description}
              </span>
            )}
          </h2>
        </div>
        <div className={`p-2 rounded-lg bg-white/5 transition-transform ${isExpanded ? 'rotate-90' : ''}`}>
          <ChevronRight size={18} className="text-white/40" />
        </div>
      </button>

      <AnimatePresence>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="overflow-hidden"
          >
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {category.components.map((component) => (
                <ComponentCard
                  key={component.path || component.name}
                  component={component}
                  color={category.color}
                  borderColor={category.borderColor}
                />
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.section>
  );
}

import { useState } from "react";
import { AnimatePresence } from "framer-motion";

export default function ComponentsPage() {
  const [activeTab, setActiveTab] = useState<"desktop" | "flutter" | "service" | "integrations">("desktop");
  
  const tabs = [
    { id: "desktop" as const, label: "Desktop", icon: Monitor, count: desktopCategories.reduce((sum, cat) => sum + cat.components.length, 0) },
    { id: "flutter" as const, label: "Mobile", icon: Smartphone, count: flutterCategories.reduce((sum, cat) => sum + cat.components.length, 0) },
    { id: "service" as const, label: "Service", icon: Server, count: backgroundServiceComponents.length },
    { id: "integrations" as const, label: "Platform", icon: Cpu, count: integrationsCount },
  ];

  return (
    <div className="space-y-24">
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center"
      >
        <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-sky-500/20 bg-sky-500/5 px-5 py-2">
          <LayoutGrid size={14} className="text-sky-400" />
          <span className="text-[10px] font-black uppercase tracking-[0.4em] text-sky-400">
            Component Inventory
          </span>
        </div>
        
        <h1 className="mb-8 text-5xl font-black uppercase tracking-tighter sm:text-7xl lg:text-8xl">
          Component Inventory
        </h1>
        
        <p className="mx-auto mb-12 max-w-3xl text-xl font-medium leading-relaxed text-white/50">
          Component inventory for Aartiq. Auto-generated by aartiq-browser/scripts/component-scanner.js. Data source: src/data/component-data.json · last scan {scan.generated.slice(0, 10)}
        </p>

        <div className="flex flex-wrap justify-center gap-3">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-3 rounded-2xl px-6 py-4 text-sm font-black uppercase tracking-wider transition-all ${
                activeTab === tab.id
                  ? "bg-sky-500 text-white shadow-lg shadow-sky-500/25"
                  : "border border-white/10 bg-white/5 text-white/60 hover:bg-white/10"
              }`}
            >
              <tab.icon size={18} />
              {tab.label}
              <span className={`rounded px-2 py-0.5 text-xs ${activeTab === tab.id ? "bg-white/20" : "bg-white/5"}`}>
                {tab.count}
              </span>
            </button>
          ))}
        </div>
      </motion.section>

      <AnimatePresence mode="wait">
        {activeTab === "desktop" && (
          <motion.div
            key="desktop"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="space-y-16"
          >
            {desktopCategories.map((category, index) => (
              <CategorySectionComponent key={category.title} category={category} index={index} />
            ))}
          </motion.div>
        )}

        {activeTab === "flutter" && (
          <motion.div
            key="flutter"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="space-y-16"
          >
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="rounded-3xl border border-white/5 bg-gradient-to-br from-purple-500/5 to-pink-500/5 p-8"
            >
              <div className="mb-8 flex items-center gap-4">
                <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-purple-500/20 to-pink-500/20 border border-purple-500/20">
                  <MonitorSmartphone size={28} className="text-purple-400" />
                </div>
                <div>
                  <p className="text-[10px] font-black uppercase tracking-[0.5em] text-white/30">
                    Flutter Mobile App
                  </p>
                  <h2 className="text-2xl font-black uppercase tracking-wider">
                    Cross-Platform Browser
                  </h2>
                </div>
              </div>
              <p className="text-white/50 mb-6">
                Full-featured mobile browser with WebView, AI chat, remote desktop control, 
                and sync with the desktop app via WebSocket.
              </p>
              <div className="flex flex-wrap gap-4 text-sm">
                <div className="flex items-center gap-2 text-white/40">
                  <Package size={16} className="text-sky-400" /> {flutterTotal} Dart files
                </div>
                <div className="flex items-center gap-2 text-white/40">
                  <Code2 size={16} className="text-emerald-400" /> {flutterTotalLines.toLocaleString()} total lines
                </div>
                <div className="flex items-center gap-2 text-white/40">
                  <Smartphone size={16} className="text-purple-400" /> iOS & Android
                </div>
              </div>
            </motion.section>

            {flutterCategories.map((category, index) => (
              <CategorySectionComponent key={category.title} category={category} index={index} />
            ))}
          </motion.div>
        )}

        {activeTab === "service" && (
          <motion.div
            key="service"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="space-y-12"
          >
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="rounded-3xl border border-white/5 bg-gradient-to-br from-emerald-500/5 to-teal-500/5 p-8"
            >
              <div className="mb-8 flex items-center gap-4">
                <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-500/20 to-teal-500/20 border border-emerald-500/20">
                  <Server size={28} className="text-emerald-400" />
                </div>
                <div>
                  <p className="text-[10px] font-black uppercase tracking-[0.5em] text-white/30">
                    Background Service
                  </p>
                  <h2 className="text-2xl font-black uppercase tracking-wider">
                    System-Level Automation
                  </h2>
                </div>
              </div>
              <p className="text-white/50 mb-6">
                Runs as an OS-level service (SYSTEM on Windows, LaunchDaemon on macOS) 
                to execute scheduled tasks even when the browser is closed. Memory footprint: ~30-50MB.
              </p>
              <div className="flex flex-wrap gap-4 text-sm">
                <div className="flex items-center gap-2 text-white/40">
                  <Timer size={16} className="text-amber-400" /> node-cron scheduler
                </div>
                <div className="flex items-center gap-2 text-white/40">
                  <Bell size={16} className="text-pink-400" /> Desktop & mobile notifications
                </div>
                <div className="flex items-center gap-2 text-white/40">
                  <RefreshCw size={16} className="text-blue-400" /> Sleep/wake recovery
                </div>
                <div className="flex items-center gap-2 text-white/40">
                  <Code2 size={16} className="text-emerald-400" /> {serviceTotalLines.toLocaleString()} total lines
                </div>
              </div>
            </motion.section>

            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {backgroundServiceComponents.map((component, index) => (
                <motion.div
                  key={component.path || component.name}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.03 }}
                >
                  <Link href={`/docs/components/${slugify(component.name)}`}>
                    <div className="h-full rounded-xl border border-white/5 bg-white/[0.02] p-5 hover:border-emerald-500/20 hover:bg-white/[0.04] transition-all">
                      <div className="flex items-center gap-3 mb-3">
                        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-500/10">
                          <Server size={18} className="text-emerald-400" />
                        </div>
                        <h3 className="font-mono text-sm font-bold text-white flex-1 truncate">
                          {component.name}
                        </h3>
                        {component.lines && (
                          <span className="shrink-0 rounded bg-white/5 px-1.5 py-0.5 text-[10px] font-mono text-white/30">
                            {component.lines} lines
                          </span>
                        )}
                      </div>
                      <p className="text-xs text-white/40 mb-3">{component.description}</p>
                      <div className="flex flex-wrap gap-1">
                        {component.tags?.map((tag) => (
                          <span key={tag} className="rounded bg-white/5 px-2 py-0.5 text-[10px] text-white/30">
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>
                  </Link>
                </motion.div>
              ))}
            </div>

            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="rounded-3xl border border-white/5 bg-white/[0.02] p-8"
            >
              <h3 className="mb-6 text-xl font-black uppercase tracking-wider">
                Service Architecture
              </h3>
              <div className="grid gap-4 sm:grid-cols-3">
                <div className="rounded-xl bg-white/5 p-4">
                  <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-sky-500/10">
                    <Play size={18} className="text-sky-400" />
                  </div>
                  <h4 className="mb-2 font-bold text-white">Task Scheduling</h4>
                  <p className="text-xs text-white/40">
                    Cron expressions define when tasks run. Supports daily, hourly, 
                    custom intervals, and one-time execution.
                  </p>
                </div>
                <div className="rounded-xl bg-white/5 p-4">
                  <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-purple-500/10">
                    <Workflow size={18} className="text-purple-400" />
                  </div>
                  <h4 className="mb-2 font-bold text-white">Task Queue</h4>
                  <p className="text-xs text-white/40">
                    Priority-based queue with exponential backoff retry. 
                    Failed tasks are logged and can be manually retried.
                  </p>
                </div>
                <div className="rounded-xl bg-white/5 p-4">
                  <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-500/10">
                    <Bell size={18} className="text-emerald-400" />
                  </div>
                  <h4 className="mb-2 font-bold text-white">Notifications</h4>
                  <p className="text-xs text-white/40">
                    Desktop notifications for task completion. 
                    Push notifications to mobile via sync service.
                  </p>
                </div>
              </div>
            </motion.section>
          </motion.div>
        )}

        {activeTab === "integrations" && (
          <motion.div
            key="integrations"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="space-y-12"
          >
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="rounded-3xl border border-orange-500/5 bg-gradient-to-br from-orange-500/5 to-blue-500/5 p-8"
            >
              <div className="mb-8 flex items-center gap-4">
                <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-orange-500/20 to-blue-500/20 border border-orange-500/20">
                  <Cpu size={28} className="text-orange-400" />
                </div>
                <div>
                  <p className="text-[10px] font-black uppercase tracking-[0.5em] text-white/30">
                    Platform Integrations
                  </p>
                  <h2 className="text-2xl font-black uppercase tracking-wider">
                    Native OS Features
                  </h2>
                </div>
              </div>

              <div className="grid gap-6 md:grid-cols-3">
                {platformIntegrations.map((platform) => {
                  const Icon = PLATFORM_ICON[platform.key] ?? Monitor;
                  return (
                    <div key={platform.key} className="rounded-2xl border border-white/10 bg-white/5 p-6">
                      <Icon size={24} className="mb-4 text-white/60" />
                      <h4 className="mb-2 font-bold text-white">{platform.title}</h4>
                      <p className="mb-4 text-xs text-white/40">{platform.blurb}</p>
                      <ul className="space-y-2 text-xs text-white/60">
                        {platform.items.map((item) => (
                          <li key={item}>• {item}</li>
                        ))}
                      </ul>
                      <Link href={platform.href} className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-orange-400 hover:text-orange-300">
                        View Docs <ChevronRight size={14} />
                      </Link>
                    </div>
                  );
                })}
              </div>
            </motion.section>

            <div className="rounded-2xl border border-white/10 bg-white/5 p-8">
              <h3 className="mb-6 text-lg font-bold text-white">Platform-Specific Automation</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-white/10">
                      <th className="pb-3 text-left text-xs font-medium text-white/40">Feature</th>
                      <th className="pb-3 text-left text-xs font-medium text-white/40">macOS</th>
                      <th className="pb-3 text-left text-xs font-medium text-white/40">Windows</th>
                      <th className="pb-3 text-left text-xs font-medium text-white/40">Linux</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5">
                    {automationMatrix.map((row) => (
                      <tr key={row.feature}>
                        <td className="py-3 text-white/60">{row.feature}</td>
                        <td className="py-3 text-white/40">{row.macos}</td>
                        <td className="py-3 text-white/40">{row.windows}</td>
                        <td className="py-3 text-white/40">{row.linux}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5 }}
        className="rounded-3xl border border-white/5 bg-white/[0.02] p-8"
      >
        <h3 className="mb-8 text-xl font-black uppercase tracking-wider">
          Quick Stats
        </h3>
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
          <div className="rounded-xl bg-white/5 p-6 text-center">
            <div className="mb-2 text-4xl font-black text-sky-400">{totalComponents}</div>
            <p className="text-sm text-white/40">Total Components</p>
          </div>
          <div className="rounded-xl bg-white/5 p-6 text-center">
            <div className="mb-2 text-4xl font-black text-emerald-400">{desktopTotal}</div>
            <p className="text-sm text-white/40">Desktop (Electron)</p>
          </div>
          <div className="rounded-xl bg-white/5 p-6 text-center">
            <div className="mb-2 text-4xl font-black text-purple-400">{flutterTotal}</div>
            <p className="text-sm text-white/40">Mobile (Flutter)</p>
          </div>
          <div className="rounded-xl bg-white/5 p-6 text-center">
            <div className="mb-2 text-4xl font-black text-amber-400">{desktopCategories.reduce((sum, cat) => sum + cat.components.reduce((lineSum, comp) => lineSum + (comp.lines || 0), 0), 0) + flutterTotalLines + backgroundServiceComponents.reduce((sum, comp) => sum + (comp.lines || 0), 0)}</div>
            <p className="text-sm text-white/40">Total Lines</p>
          </div>
        </div>
        <p className="text-xs text-white/40 mt-4 text-center">
          Line counts auto-generated by aartiq-browser/scripts/component-scanner.js
        </p>
      </motion.section>

      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.55 }}
        className="rounded-3xl border border-sky-500/20 bg-sky-500/5 p-8"
      >
        <div className="flex items-center gap-4 mb-6">
          <Terminal size={24} className="text-sky-400" />
          <h3 className="text-xl font-black uppercase tracking-wider">
            Auto-Update Component Data
          </h3>
        </div>
        <p className="text-white/60 mb-6">
          Run the component scanner to update line counts and metadata:
        </p>
        <div className="bg-black/40 rounded-xl p-4 font-mono text-sm">
          <div className="text-white/40 mb-2"># Scan all components (desktop + Flutter)</div>
          <div className="text-sky-400">cd aartiq-browser && node scripts/component-scanner.js --all</div>
          <div className="text-white/40 mt-4 mb-2"># Check for undocumented components</div>
          <div className="text-sky-400">node scripts/component-scanner.js --missing</div>
          <div className="text-emerald-400 mt-4 text-xs">
            <RefreshCw size={12} className="inline mr-1" />
            Stats auto-sync from src/data/component-data.json on page load.
          </div>
        </div>
        <p className="text-xs text-white/40 mt-4">
          Line counts auto-generated by aartiq-browser/scripts/component-scanner.js
        </p>
      </motion.section>
    </div>
  );
}
